SECRET_KEY = 'SECRET_KEY'
MONGODB_URL = 'mongodb://localhost/'
MONGODB_NAME = 'databasic-dev'
GOOGLE_CLIENT_ID = "MY_CLIENT_ID"
GOOGLE_CLIENT_SECRET = "MY_SECRET_ID"
GOOGLE_ANALYTICS_ID = ''
DEBUG = True